const FooterData = {
  "Life Insurance": [
    "Life Insurance",
    "Term Insurance",
    "Term Insurance Calculator",
    "1 Crore Term Insurance",
    "Term Return of Premium",
    "Spouse Term Plan",
  ],
  "Other Insurance": [
    "Group Health Insurance",
    "Cyber Insurance",
    "D&O Insurance",
    "Workers Compensation",
    "Business Insurance",
    "Cancer Insurance",
    "Home Insurance",
  ],
  "Health Insurance": [
    "Health Insurance",
    "1 Cr Health Cover",
    "Family Health Insurance",
    "Senior Citizen Health Insurance",
    "Coronavirus Insurance",
    "Corona Kavach Policy",
    "Corona Rakshak Policy",
    "Arogya Sabjeevani Policy",
  ],
  Investment: [
    "Investment Plans",
    "Capital Guarantee Plans",
    "Investment Plans for NRIs",
    "Child Plans",
    "Pension Plans",
    "Gauranteed Return Plans",
    "Tax Savinng Investments",
    "Market Linked Investment Plan",
    "(ULIP)",
    "SIP(Systematic Investment Plan)",
    "Endownment Policy",
    "LIC",
  ],
  "General Insurance": [
    "Car Insurance",
    "Bike Insurance",
    "Motor Insurance",
    "Third Party Car Insurance",
    "Third Party Bike Insurance",
    "Travel Insurance",
    "Commercial Vehicle Insurance",
  ],
};
export default FooterData;
